// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snakes.proto

/*
Package snakes is a generated protocol buffer package.

It is generated from these files:
	snakes.proto

It has these top-level messages:
	Snake
*/
package snakes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Snake struct {
	VelocityX float32        `protobuf:"fixed32,1,opt,name=VelocityX" json:"VelocityX,omitempty"`
	VelocityY float32        `protobuf:"fixed32,2,opt,name=VelocityY" json:"VelocityY,omitempty"`
	Length    int32          `protobuf:"varint,3,opt,name=Length" json:"Length,omitempty"`
	Symbol    int32          `protobuf:"varint,4,opt,name=Symbol" json:"Symbol,omitempty"`
	Tail      []*Snake_Point `protobuf:"bytes,5,rep,name=Tail" json:"Tail,omitempty"`
}

func (m *Snake) Reset()                    { *m = Snake{} }
func (m *Snake) String() string            { return proto.CompactTextString(m) }
func (*Snake) ProtoMessage()               {}
func (*Snake) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Snake) GetVelocityX() float32 {
	if m != nil {
		return m.VelocityX
	}
	return 0
}

func (m *Snake) GetVelocityY() float32 {
	if m != nil {
		return m.VelocityY
	}
	return 0
}

func (m *Snake) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Snake) GetSymbol() int32 {
	if m != nil {
		return m.Symbol
	}
	return 0
}

func (m *Snake) GetTail() []*Snake_Point {
	if m != nil {
		return m.Tail
	}
	return nil
}

type Snake_Point struct {
	X float32 `protobuf:"fixed32,1,opt,name=X" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y" json:"Y,omitempty"`
}

func (m *Snake_Point) Reset()                    { *m = Snake_Point{} }
func (m *Snake_Point) String() string            { return proto.CompactTextString(m) }
func (*Snake_Point) ProtoMessage()               {}
func (*Snake_Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Snake_Point) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Snake_Point) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Snake)(nil), "Snake")
	proto.RegisterType((*Snake_Point)(nil), "Snake.Point")
}

func init() { proto.RegisterFile("snakes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0x4b, 0xcc,
	0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xda, 0xc5, 0xc8, 0xc5, 0x1a, 0x0c, 0x12,
	0x10, 0x92, 0xe1, 0xe2, 0x0c, 0x4b, 0xcd, 0xc9, 0x4f, 0xce, 0x2c, 0xa9, 0x8c, 0x90, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0a, 0x42, 0x08, 0x20, 0xcb, 0x46, 0x4a, 0x30, 0xa1, 0xca, 0x46, 0x0a, 0x89,
	0x71, 0xb1, 0xf9, 0xa4, 0xe6, 0xa5, 0x97, 0x64, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0xb0, 0x06, 0x41,
	0x79, 0x20, 0xf1, 0xe0, 0xca, 0xdc, 0xa4, 0xfc, 0x1c, 0x09, 0x16, 0x88, 0x38, 0x84, 0x27, 0xa4,
	0xc0, 0xc5, 0x12, 0x92, 0x98, 0x99, 0x23, 0xc1, 0xaa, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa3, 0x07,
	0x76, 0x81, 0x5e, 0x40, 0x7e, 0x66, 0x5e, 0x49, 0x10, 0x58, 0x46, 0x4a, 0x99, 0x8b, 0x15, 0xcc,
	0x15, 0xe2, 0xe1, 0x62, 0x84, 0x39, 0x87, 0x31, 0x02, 0xc4, 0x83, 0x59, 0xcf, 0x18, 0x99, 0xc4,
	0x06, 0xf6, 0x83, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xad, 0xcf, 0x42, 0x15, 0xd3, 0x00, 0x00,
	0x00,
}
